### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement ipython:=7.21.9 https://github.com/norkator/open-intelligence#python-side

### ISSUE THREAD

**Issue by AckeemPratt** [norkator/open-intelligence#157]
![image](https://user-images.githubusercontent.com/45286873/125846641-29ea85e0-0dee-4f75-9725-faad9c25f70a.png)
![image](https://user-images.githubusercontent.com/45286873/125846655-f5d5de70-687a-4f99-b992-5db50ffcd8bb.png)

For here, I am not sure where I should run the bat file from.  https://github.com/norkator/open-intelligence#python-side
![image](https://user-images.githubusercontent.com/45286873/125846927-f0d594a8-c8a5-4540-9aff-5661f954e5c5.png)

I tried these steps: https://www.educative.io/edpresso/how-to-activate-virtualenv-windows
This is where I am at now; please help me. https://github.com/norkator/open-intelligence#python-side

**Comment by norkator** [comment]
@AckeemPratt I see /venv folder at root of project when virtual env is created with same steps as your link how to set it up. You call that activate.bat from root of this project folder, then you see at terminal beginning saying its ysing it.

How many different python versions you have? If you have more than one, then you need to investigate how to choose 3.6

**Comment by norkator** [comment]
@AckeemPratt what comes to a "could not find version that satifies..." Sounds like wrong python version.

**Comment by norkator** [comment]
@AckeemPratt In your image you have requirements.txt with contents which makes no sense. All package names there has nothing to do with this repository.

**Comment by AckeemPratt** [comment]
Thank you for your response @norkator I have python 3.6 installed. Do I need to possibly upgrade even though you had use this version?

**Comment by norkator** [comment]
> Thank you for your response @norkator I have python 3.6 installed. Do I need to possibly upgrade even though you had use this version?

Only 3.6 works with this project dependencies. I tried with 3.8 some time ago but it was a big mess requiring huge rewrites.

**Comment by AckeemPratt** [comment]
Ok, I am using 3.6.0; this is quite strange.

**Comment by norkator** [comment]
> Ok, I am using 3.6.0; this is quite strange.

But you have requirements.txt inside /api/front-end folder, what is that? Its not part of this project.

**Comment by AckeemPratt** [comment]
Can I share my screen with you? https://meet.google.com/zno-juku-ozn

**Comment by AckeemPratt** [comment]
> > Ok, I am using 3.6.0; this is quite strange.
> 
> But you have requirements.txt inside /api/front-end folder, what is that? Its not part of this project.

I pulled it from github

**Comment by AckeemPratt** [comment]
Cloned i.e

**Comment by norkator** [comment]
> > > Ok, I am using 3.6.0; this is quite strange.
> > 
> > 
> > But you have requirements.txt inside /api/front-end folder, what is that? Its not part of this project.
> 
> I pulled it from github

I dont find it at all from this repository. Did you clone some fork?

This https://github.com/norkator/open-intelligence/blob/master/requirements_windows.txt is what you should be installing with pip install -r requirements_windows.txt

**Comment by AckeemPratt** [comment]
possibly a form let me clone the project once more.

**Comment by AckeemPratt** [comment]
fork*

**Comment by norkator** [comment]
Sorry, not joining meetings. Readme is still valid, running requirements install as told in readme should do the trick. What you are running/installing just does not exists in this repo.

**Comment by AckeemPratt** [comment]
Ok I starting it fresh thank you I will keep you posted.

**Comment by norkator** [comment]
> Ok I starting it fresh thank you I will keep you posted.

Hows problem solving progressing?
